function fitresult1 = createFit_K40(t, ambient_spectrum)
%CREATEFIT3(T,AMBIENT_SPECTRUM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: ambient_spectrum
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Apr-2023 19:03:34


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, ambient_spectrum );

% Set up fittype and options.
ft = fittype( 'gauss5' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [5015 40 22.7896358341724 3332.90108600426 73 25.6651224688489 1727.50740911849 111 31.2080617265838 1392 452 24.2342803102739 1332.98547232123 180 35.6114323418388];

% Fit model to data.
fitresult1 = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
%h = plot( fitresult, xData, yData );
%legend( h, 'ambient_spectrum vs. t', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
%xlabel( 't', 'Interpreter', 'none' );
%ylabel( 'ambient_spectrum', 'Interpreter', 'none' );
%grid on


