function fitresult5 = createFit_Co60_2(t, isotope_spectrum2)
%CREATEFIT3(T,ISOTOPE_SPECTRUM2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: isotope_spectrum2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Apr-2023 19:57:55


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, isotope_spectrum2 );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [223 771 57.99932974938];

% Fit model to data.
fitresult5 = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
%h = plot( fitresult, xData, yData );
%legend( h, 'isotope_spectrum2 vs. t', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
%xlabel( 't', 'Interpreter', 'none' );
%ylabel( 'isotope_spectrum2', 'Interpreter', 'none' );
%grid on


