function fitresult = createFit_Eu152_1_2(t, isotope_spectrum1)
%CREATEFIT3(T,ISOTOPE_SPECTRUM1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: isotope_spectrum1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Apr-2023 13:48:15


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, isotope_spectrum1 );

% Set up fittype and options.
ft = fittype( 'gauss8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [13930 100 9.70202713717035 11731 33 13.1011827292289 10064.3192154311 69 13.2810547116168 6039 330 10.7639086760685 5225 234 12.2856002426357 4926.78319160073 52 22.744549786897 4849.99924851442 287 14.2055533726892 4639.56722624733 128 20.4230079900292];

% Fit model to data.
fitresult = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
%h = plot( fitresult, xData, yData );
%legend( h, 'isotope_spectrum1 vs. t', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
%xlabel( 't', 'Interpreter', 'none' );
%ylabel( 'isotope_spectrum1', 'Interpreter', 'none' );
%grid on


