function fitresult2 = kalibrovka_gs(c_gauss, e)
%CREATEFIT(C_GAUSS,E)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : c_gauss
%      Y Output: e
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-May-2023 15:40:05


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( c_gauss, e );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.781487818297422 1.64292431135837];

% Fit model to data.
fitresult2 = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult2, xData, yData );
legend( h, 'e vs. c_gauss', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'c_gauss', 'Interpreter', 'none' );
ylabel( 'e', 'Interpreter', 'none' );
grid on


